#!/usr/bin/env python3
# Copyright 2026 KYNODE
# Licensed under the Apache License, Version 2.0.

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


COMPONENT_PATHS = {
    "growth-curves": ("prefix", "packages/growth-curves/src/"),
    "triage-ranges": ("prefix", "packages/triage-ranges/src/"),
    "anomaly-detection": ("prefix", "packages/anomaly-detection/src/"),
    "vaccinations": ("prefix", "packages/vaccinations/src/"),
    "local-node": ("prefix", "apps/local-node/src/"),
    "brief": (
        "exact",
        "apps/local-node/src/kynode_pediatric_local_node/brief.py",
    ),
}


def color_for(percent: int) -> str:
    if percent >= 90:
        return "brightgreen"
    if percent >= 80:
        return "green"
    if percent >= 70:
        return "yellow"
    return "red"


def badge_payload(coverage: dict[str, object]) -> dict[str, object]:
    percent = round(float(coverage["totals"]["percent_covered"]))
    return {
        "schemaVersion": 1,
        "label": "coverage",
        "message": f"{percent}%",
        "color": color_for(percent),
    }


def _matches_component(path: str, matcher: tuple[str, str]) -> bool:
    match_type, value = matcher
    if match_type == "exact":
        return path == value
    return path.startswith(value)


def _component_summary(
    files: dict[str, object],
    matcher: tuple[str, str],
) -> dict[str, int]:
    summaries = [
        details["summary"]
        for path, details in files.items()
        if _matches_component(path, matcher)
    ]
    if not summaries:
        raise ValueError(f"No coverage files matched {matcher[1]!r}")

    statements = sum(int(summary["num_statements"]) for summary in summaries)
    covered = sum(int(summary["covered_lines"]) for summary in summaries)
    percent = round((covered / statements) * 100) if statements else 100
    return {
        "coverage_percent": percent,
        "covered_statements": covered,
        "statements": statements,
    }


def components_payload(coverage: dict[str, object]) -> dict[str, object]:
    files = coverage["files"]
    totals = coverage["totals"]
    return {
        "schema_version": 1,
        "source": "coverage.py JSON generated by the public CI workflow",
        "global": {
            "coverage_percent": round(float(totals["percent_covered"])),
            "covered_statements": int(totals["covered_lines"]),
            "statements": int(totals["num_statements"]),
        },
        "components": {
            name: _component_summary(files, matcher)
            for name, matcher in COMPONENT_PATHS.items()
        },
    }


def _expected_json(payload: dict[str, object]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _check_current(path: Path, expected: str) -> bool:
    if not path.exists() or path.read_text(encoding="utf-8") != expected:
        print(
            f"{path} is out of date. Run scripts/update_coverage_badge.py.",
            file=sys.stderr,
        )
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Update or check public coverage evidence generated by CI."
    )
    parser.add_argument("coverage_json", type=Path)
    parser.add_argument("badge_json", type=Path)
    parser.add_argument(
        "--components-json",
        type=Path,
        help="Write or verify the machine-readable per-component coverage manifest.",
    )
    parser.add_argument("--check", action="store_true", help="Fail if the badge JSON is not current.")
    args = parser.parse_args()

    coverage = json.loads(args.coverage_json.read_text(encoding="utf-8"))
    expected_badge = _expected_json(badge_payload(coverage))
    expected_components = (
        _expected_json(components_payload(coverage))
        if args.components_json
        else None
    )

    if args.check:
        current = _check_current(args.badge_json, expected_badge)
        if args.components_json and expected_components is not None:
            current = _check_current(args.components_json, expected_components) and current
        return 0 if current else 1

    args.badge_json.parent.mkdir(parents=True, exist_ok=True)
    args.badge_json.write_text(expected_badge, encoding="utf-8")
    if args.components_json and expected_components is not None:
        args.components_json.parent.mkdir(parents=True, exist_ok=True)
        args.components_json.write_text(expected_components, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
